Feature/54500 add built in device classes
wirenboard/wb-mqtt-smartweb pull request #11
Opened 2022-10-31 13:01 UTC by rkochkin

* Добавил тесты для LoadConfig().
* Переделал работу с директориями и файлами на std::filesystem.

2022-10-31 17:22 UTC, sikmir commented on src/config_parser.cpp
> +#include <experimental/filesystem>
Можно на с++17 переключиться и использовать без experimental.

2022-10-31 17:28 UTC, sikmir commented on src/config_parser.cpp
> +            for (auto& entry: std::experimental::filesystem::directory_iterator(dirPath)) {
```suggestion
            for (const auto& entry: std::experimental::filesystem::directory_iterator(dirPath)) {
```

2022-11-01 06:20 UTC, rkochkin commented on src/config_parser.cpp
> +#include <experimental/filesystem>
gcc(6.3) из stretch поддерживает стандарт C++17 не полностью. В частности не хватает атрибутов, структурных биндингов. Можно посмотреть чего не хватает в https://gcc.gnu.org/projects/cxx-status.html
Хотя для filesystem это должно работать, но
можно получить несовместимый код для stretch и bullseye, потому как для bullseye все возможности С++17 доступны.
@webconn что скажешь?

2022-11-01 06:24 UTC, webconn commented on src/config_parser.cpp
> +#include <experimental/filesystem>
Ну с тем учётом, что нам это надо в текущий релиз бэкпортировать, и мы это сможем сделать через fast-forward, то лучше experimental пока оставить.

2022-11-01 06:26 UTC, sikmir commented on src/config_parser.cpp
> +#include <experimental/filesystem>
mqtt-serial (и mqtt-gpio) уже использует c++17, и тот же std::filesystem используется там.

2022-11-01 06:30 UTC, webconn commented on src/config_parser.cpp
> +#include <experimental/filesystem>
Да, но там релизные версии (из ветки `release/wb-2207`) уже разошлись с `master` (потому там в `master` мы всё перетащили на bullseye), а тут ещё нет, и коммит в `master` легко можно превратить в версию, пригодную для бэкпорта в 2207. Более того, я предполагаю, что изменения в этот пакет мы в ближайшее время вносить не будем, так что нет смысла тратить на него время. Когда bullseye станет стабильным и понадобится тут что-то поменять - придём и поменяем

2022-11-01 07:09 UTC, rkochkin commented on src/config_parser.cpp
> +            for (auto& entry: std::experimental::filesystem::directory_iterator(dirPath)) {
Спасибо, поправил.

2022-11-07 04:36 UTC, KraPete requested changes
Ты с тепломонитором связывался, уверен, что эти 3 класса корректные?

2022-11-07 04:36 UTC, KraPete commented on debian/changelog
> +  * Add built-in device class directory
Этот текст попадает в ChangeLog релиза, его читает тех.поддержка, а потом клиенты. Я всегда предлагаю писать тут то, что изменилось для клиента, максимально понятням для неподготовленного человек текстом.
Потому предлагаю написать, что в /usr появились описания классов, которые будут идти вместе с пакетом. Описания в /etc остались для экспериментов. Добавили классы такие-то.
А всё про переход на std::filesystem и тонкости внутренней реализации описывать в commit message.

2022-11-07 04:36 UTC, KraPete commented on src/config_parser.cpp
> +            for (const auto& entry: std::experimental::filesystem::directory_iterator(dirPath)) {
Давай, это в отдельную функцию вынесем. Уже почти в каждом проекте такая есть. Может, завести задачу на включение функции обхода кaталога в libwbmqtt1?

2022-11-07 04:36 UTC, KraPete commented on src/SmartWebToMqttGateway.h
> +enum class TDeviceClassOwner
Зачем это? Почему нельзя просто загрузить всё из /usr, а потом из /etc.
Если имя класса совпадает, то писать, что используем переопреденение по такому-то пути?

2022-11-07 04:36 UTC, KraPete commented on src/config_parser.cpp
> +            if (owner != TDeviceClassOwner::USER) {
Тут мы в лог можем написать, что переопределили, а ничего не сделать.

2022-11-07 07:09 UTC, sikmir commented on src/config_parser.cpp
> +                if (entry.status().type() == std::experimental::filesystem::file_type::regular &&
1. Тут `regex_search` избыточно, можно просто сравнить `entry.path().extension() == ...`.
2. Можно использовать `std::experimental::filesystem::is_regular_file(entry)` вместо первого сравнения.

2022-11-07 07:12 UTC, sikmir commented on src/config_parser.cpp
> +                        continue;
```suggestion
```

2022-11-07 07:14 UTC, sikmir commented on src/config_parser.cpp
> +            LOG(WBMQTT::Error) << "Cannot open " + classesDir + " directory: " << ex.what();
```suggestion
            LOG(WBMQTT::Error) << "Cannot open " << classesDir << " directory: " << ex.what();
```

2022-11-08 12:35 UTC, rkochkin commented on src/config_parser.cpp
> +                if (entry.status().type() == std::experimental::filesystem::file_type::regular &&
Спасибо, поправил.

2022-11-08 12:35 UTC, rkochkin commented on src/config_parser.cpp
> +                        continue;
Убрал

2022-11-08 13:06 UTC, rkochkin commented on debian/changelog
> +  * Add built-in device class directory
Поправил

2022-11-08 15:03 UTC, rkochkin commented on src/config_parser.cpp
> +            for (const auto& entry: std::experimental::filesystem::directory_iterator(dirPath)) {
Вынес в отдельную функцию

2022-11-08 16:01 UTC, rkochkin commented on src/SmartWebToMqttGateway.h
> +enum class TDeviceClassOwner
> Зачем это? Почему нельзя просто загрузить всё из /usr, а потом из /etc.
В старом коде есть проверка дублирования классов. Так как был один каталог, классы перед добавлением проверялись на наличие в мапе.
Для сохранения этой логики сделал аргумент, указывающий на тип директории откуда считывается. И в LoadSmartWebClass() уже принимается решение генерировать ошибку о дублировании или переписать класс.
Можно это как-то переделать, но не стал менять архитектуру, просто добавил параметр.  И я думаю полезно знать из какого каталога класс.

2022-11-08 16:48 UTC, rkochkin commented on src/config_parser.cpp
> +            if (owner != TDeviceClassOwner::USER) {
Поправил.

2022-11-09 12:24 UTC, rkochkin commented
> Ты с тепломонитором связывался, уверен, что эти 3 класса корректные?

С представителем тепломонитора решили, что добавим все 8 файлов шаблонов из [описания](http://gidrologo.ru/%D0%BA%D0%B0%D1%82%D0%B0%D0%BB%D0%BE%D0%B3/%D0%B0%D0%B2%D1%82%D0%BE%D0%BC%D0%B0%D1%82%D0%B8%D0%BA%D0%B0/%D1%83%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5/smartweb/wirenboard_6#%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0_%D0%B4%D1%80%D0%B0%D0%B9%D0%B2%D0%B5%D1%80%D0%B0_wb-mqtt-smartweb).

2022-11-10 07:21 UTC, sikmir commented on src/config_parser.cpp
> +            const auto fileName = entry.path().string();
`fileName` теперь нигде не используется.

2022-11-10 07:27 UTC, sikmir commented on src/config_parser.cpp
> +        if(configJson.isMember("debug")) {
```suggestion
        if (configJson.isMember("debug")) {
```
`clang-format` будет ругаться

2022-11-10 07:38 UTC, rkochkin commented on src/config_parser.cpp
> +            const auto fileName = entry.path().string();
Поправил

2022-11-10 07:39 UTC, rkochkin commented on src/config_parser.cpp
> +        if(configJson.isMember("debug")) {
Поправил

2022-11-11 07:21 UTC, webconn requested changes
Я бы ещё JSON прогнал через какой-нибудь форматтер, а то в диффе на гитхабе выглядит неопрятно

2022-11-11 08:45 UTC, rkochkin commented on test/config.test.cpp
> +        EXPECT_LE(1, pConfig->Classes.size());
Добавил проверку на ожидаемое количество классов.

2022-11-11 08:46 UTC, rkochkin commented on src/config_parser.cpp
> +    const auto programName = data["class"].asString();
Переименовал

2022-11-11 08:46 UTC, rkochkin commented on src/SmartWebToMqttGateway.h
> +enum class TDeviceClassOwner
Переименовал

2022-11-11 08:49 UTC, rkochkin commented on test/config_test_data/test_config.json
> +                    "channel": "wb-adc/R1",
Скопировал тестовый конфиг из корня проекта, который устанавливается /etc/wb-mqtt-smartweb.conf вместе с пакетом. Проверку схемой конфига проходит.

2022-11-11 09:32 UTC, rkochkin commented
> Я бы ещё JSON прогнал через какой-нибудь форматтер, а то в диффе на гитхабе выглядит неопрятно

Классы устройств взяты с сайта тепломонитора в исходном виде. Лучше их оставить как есть.

Вообще весь код нужно прогнать через clang форматтер. Сейчас он не проверяется на формат.
Но как понимаю это нужно делать отдельным PR.

2022-11-11 09:32 UTC, rkochkin commented on src/config_parser.cpp
> +            if (owner != TDeviceClassOwner::USER) {
Написал комментарий у переделал, чтобы было чуть понятнее, надеюсь.

2022-11-14 07:34 UTC, KraPete approved these changes

2022-11-14 11:55 UTC, merged